# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "./tmp/server"

# Logger.
[logger]
    Path        = "./tmp/log"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
#     Delimiters  =  '["{{", "}}"]'

# Database.
[database]
    link  = "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "./tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link   = "mysql:root:root@tcp(127.0.0.1:3306)/test"
        group  = ""
        prefix = ""
        tables = ""
    [gfcli.build]
         name     = "myapp"
         arch     = "amd64"
         system   = "linux"
         mod      = "none"
         cgo      = 0
         pack     = "config,public,template"
#          version  = "v1.0.0"
         output   = "./bin"
         extra    = ""