// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-demo/app/dao/internal"
)

// itemDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type itemDao struct {
	*internal.ItemDao
}

var (
	// Item is globally public accessible object for table item operations.
	Item = itemDao{
		internal.NewItemDao(),
	}
)

// Fill with you ideas below.
